<?xml version="1.0" encoding="UTF-8"?>
<!--Designed and generated by Altova StyleVision Enterprise Edition 2014 - see http://www.altova.com/stylevision for more information.-->
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:altova="http://www.altova.com" xmlns:altovaext="http://www.altova.com/xslt-extensions" xmlns:clitype="clitype" xmlns:fn="http://www.w3.org/2005/xpath-functions" xmlns:iso4217="http://www.xbrl.org/2003/iso4217" xmlns:ix="http://www.xbrl.org/2008/inlineXBRL" xmlns:java="java" xmlns:link="http://www.xbrl.org/2003/linkbase" xmlns:sps="http://www.altova.com/StyleVision/user-xpath-functions" xmlns:xbrldi="http://xbrl.org/2006/xbrldi" xmlns:xbrli="http://www.xbrl.org/2003/instance" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" exclude-result-prefixes="altova altovaext clitype fn iso4217 ix java link sps xbrldi xbrli xlink xs xsi">
	<xsl:output version="4.0" method="html" indent="no" encoding="UTF-8" doctype-public="-//W3C//DTD HTML 4.01 Transitional//EN" doctype-system="http://www.w3.org/TR/html4/loose.dtd"/>
	<xsl:param name="SV_OutputFormat" select="'HTML'"/>
	<xsl:variable name="XML" select="/"/>
	<xsl:variable name="altova:nPxPerIn" select="96"/>
	<xsl:template match="/">
		<html>
			<head>
				<title/>
				<meta name="generator" content="Altova StyleVision Enterprise Edition 2013 rel. 2 sp1 (http://www.altova.com)"/>
				<meta http-equiv="X-UA-Compatible" content="IE=9"/>
				<xsl:comment>[if IE]&gt;&lt;STYLE type=&quot;text/css&quot;&gt;.altova-rotate-left-textbox{filter: progid:DXImageTransform.Microsoft.BasicImage(rotation=3)} .altova-rotate-right-textbox{filter: progid:DXImageTransform.Microsoft.BasicImage(rotation=1)} &lt;/STYLE&gt;&lt;![endif]</xsl:comment>
				<xsl:comment>[if !IE]&gt;&lt;!</xsl:comment>
				<style type="text/css">.altova-rotate-left-textbox{-webkit-transform: rotate(-90deg) translate(-100%, 0%); -webkit-transform-origin: 0% 0%;-moz-transform: rotate(-90deg) translate(-100%, 0%); -moz-transform-origin: 0% 0%;-ms-transform: rotate(-90deg) translate(-100%, 0%); -ms-transform-origin: 0% 0%;}.altova-rotate-right-textbox{-webkit-transform: rotate(90deg) translate(0%, -100%); -webkit-transform-origin: 0% 0%;-moz-transform: rotate(90deg) translate(0%, -100%); -moz-transform-origin: 0% 0%;-ms-transform: rotate(90deg) translate(0%, -100%); -ms-transform-origin: 0% 0%;}</style>
				<xsl:comment>&lt;![endif]</xsl:comment>
				<style type="text/css">@page { margin-left:0.6in; margin-right:0.6in; margin-top:0.79in; margin-bottom:0.79in } @media print { br.altova-page-break { page-break-before: always; } }</style>
			</head>
			<body>
				<xsl:for-each select="$XML">
					<xsl:variable name="ShowExpenseSplit" select="true()"/>
					<xsl:variable name="ExpenseSplitBy" select="&apos;type&apos;"/>
					<xsl:for-each select="marketing-expenses">
						<br/>
						<table style="border-collapse:collapse; " border="0" cellpadding="0" cellspacing="0" width="100%">
							<xsl:variable name="altova:CurrContextGrid_0" select="."/>
							<tbody>
								<tr>
									<td style="border-bottom-color:#0588BA; border-bottom-style:solid; border-bottom-width:medium; ">
										<img style="height:76px; width:153px; " border="0">
											<xsl:attribute name="src">
												<xsl:if test="substring(string(&apos;http://www.nanonull.com/nanonull.gif&apos;), 2, 1) = ':'">
													<xsl:text>file:///</xsl:text>
												</xsl:if>
												<xsl:value-of select="translate(string(&apos;http://www.nanonull.com/nanonull.gif&apos;), '&#x5c;', '/')"/>
											</xsl:attribute>
											<xsl:attribute name="alt"/>
										</img>
									</td>
								</tr>
							</tbody>
						</table>
						<xsl:choose>
							<xsl:when test="count( expense-item ) &gt; 0">
								<table border="0" cellspacing="0" width="100%">
									<xsl:variable name="altova:CurrContextGrid_1" select="."/>
									<tbody>
										<tr>
											<td align="left" valign="top" width="85%">
												<span style="font-size:20pt; font-weight:bold; margin-top:3pt; ">
													<xsl:text>Marketing Expense Report</xsl:text>
												</span>
											</td>
											<td bgcolor="#D2FFFF" nowrap="set" width="15%">
												<span style="font-family:Tahoma; font-size:10pt; font-weight:bold; ">
													<xsl:text>Total:&#160; </xsl:text>
												</span>
												<span style="font-family:Tahoma; font-size:10pt; ">
													<xsl:variable name="altova:seqContentStrings_2">
														<xsl:value-of select="format-number(number(sum( expense-item/expense  )), '###,##0.00')"/>
													</xsl:variable>
													<xsl:variable name="altova:sContent_2" select="string($altova:seqContentStrings_2)"/>
													<xsl:value-of select="$altova:sContent_2"/>
												</span>
												<span style="font-family:Tahoma; font-size:10pt; ">
													<xsl:text> $</xsl:text>
												</span>
											</td>
										</tr>
										<tr>
											<td width="85%"/>
											<td bgcolor="#D2FFFF" width="15%"/>
										</tr>
									</tbody>
								</table>
							</xsl:when>
							<xsl:otherwise>
								<table border="0" width="100%">
									<xsl:variable name="altova:CurrContextGrid_3" select="."/>
									<tbody>
										<tr>
											<td align="left" valign="top" width="100%">
												<span style="font-size:20pt; font-weight:bold; margin-top:3pt; ">
													<xsl:text>Marketing Expense Report</xsl:text>
												</span>
											</td>
										</tr>
										<tr>
											<td width="100%"/>
										</tr>
									</tbody>
								</table>
							</xsl:otherwise>
						</xsl:choose>
						<table style="border-collapse:collapse; table-layout:fixed; " border="0" cellpadding="0" cellspacing="0" width="100%">
							<xsl:variable name="altova:CurrContextGrid_4" select="."/>
							<tbody>
								<tr>
									<td style="border-bottom-color:black; border-bottom-style:solid; border-bottom-width:1pt; " bgcolor="#D2FFFF">
										<span style="font-family:Verdana; font-size:14pt; ">
											<xsl:text>Employee Information</xsl:text>
										</span>
									</td>
								</tr>
							</tbody>
						</table>
						<xsl:for-each select="Person">
							<table style="border-collapse:collapse; " border="0" cellpadding="0" cellspacing="0" width="100%">
								<xsl:variable name="altova:CurrContextGrid_5" select="."/>
								<tbody>
									<tr>
										<td width="2%"/>
										<td width="48%">
											<table border="0" width="100%">
												<xsl:variable name="altova:CurrContextGrid_6" select="."/>
												<tbody>
													<tr>
														<td style="border-color:#D3D3D3; border-style:solid; border-width:1pt; width:auto; " bgcolor="#F3F3F3" width="50%">
															<xsl:for-each select="FullName">
																<xsl:apply-templates/>
															</xsl:for-each>
														</td>
													</tr>
													<tr>
														<td style="width:auto; " width="50%">
															<xsl:choose>
																<xsl:when test="string-length( FullName ) &gt; 0">
																	<span style="font-family:Arial; font-size:10pt; font-weight:bold; ">
																		<xsl:text>Name</xsl:text>
																	</span>
																</xsl:when>
																<xsl:otherwise>
																	<span style="color:#FF0000; font-family:Arial; font-size:10pt; font-weight:bold; ">
																		<xsl:text>First Name is required</xsl:text>
																	</span>
																</xsl:otherwise>
															</xsl:choose>
														</td>
													</tr>
												</tbody>
											</table>
										</td>
										<td width="48%">
											<table border="0" width="100%">
												<xsl:variable name="altova:CurrContextGrid_7" select="."/>
												<tbody>
													<tr>
														<td style="border-color:#D3D3D3; border-style:solid; border-width:1pt; " bgcolor="#F3F3F3">
															<xsl:for-each select="Title">
																<xsl:apply-templates/>
															</xsl:for-each>
														</td>
													</tr>
													<tr>
														<td>
															<span style="font-family:Arial; font-size:10pt; font-weight:bold; ">
																<xsl:text>Title</xsl:text>
															</span>
														</td>
													</tr>
												</tbody>
											</table>
										</td>
										<td width="2%"/>
									</tr>
									<tr>
										<td width="2%"/>
										<td width="48%">
											<table border="0" width="100%">
												<xsl:variable name="altova:CurrContextGrid_8" select="."/>
												<tbody>
													<tr>
														<td style="border-color:#D3D3D3; border-style:solid; border-width:1pt; " bgcolor="#F3F3F3">
															<xsl:for-each select="Email">
																<xsl:apply-templates/>
															</xsl:for-each>
														</td>
													</tr>
													<tr>
														<td>
															<xsl:choose>
																<xsl:when test="string-length( Email ) &gt; 0">
																	<span style="font-family:Arial; font-size:10pt; font-weight:bold; ">
																		<xsl:text>E-Mail</xsl:text>
																	</span>
																</xsl:when>
																<xsl:otherwise>
																	<span style="color:#FF0000; font-family:Arial; font-size:10pt; font-weight:bold; ">
																		<xsl:text>E-Mail is required</xsl:text>
																	</span>
																</xsl:otherwise>
															</xsl:choose>
														</td>
													</tr>
												</tbody>
											</table>
										</td>
										<td width="48%">
											<table border="0" width="100%">
												<xsl:variable name="altova:CurrContextGrid_9" select="."/>
												<tbody>
													<tr>
														<td style="border-color:#D3D3D3; border-style:solid; border-width:1pt; " bgcolor="#F3F3F3">
															<xsl:for-each select="Phone">
																<xsl:apply-templates/>
															</xsl:for-each>
														</td>
													</tr>
													<tr>
														<td>
															<span style="font-family:Arial; font-size:10pt; font-weight:bold; ">
																<xsl:text>Phone</xsl:text>
															</span>
														</td>
													</tr>
												</tbody>
											</table>
										</td>
										<td width="2%"/>
									</tr>
								</tbody>
							</table>
						</xsl:for-each>
						<br/>
						<xsl:if test="count( expense-item ) &gt; 0">
							<table style="border-collapse:collapse; table-layout:fixed; " border="0" cellpadding="0" cellspacing="0" width="100%">
								<xsl:variable name="altova:CurrContextGrid_10" select="."/>
								<tbody>
									<tr style="height:24px; ">
										<td style="border-bottom-color:black; border-bottom-style:solid; border-bottom-width:1pt; " bgcolor="#D2FFFF">
											<span style="font-family:Verdana; font-size:14pt; ">
												<xsl:text>Expense List</xsl:text>
											</span>
										</td>
									</tr>
								</tbody>
							</table>
							<table border="0" width="100%">
								<xsl:variable name="altova:CurrContextGrid_11" select="."/>
								<thead>
									<tr bgcolor="#C0C0C0">
										<th style="width:auto; " align="left">
											<span style="font-family:Arial; font-size:10pt; font-weight:bold; ">
												<xsl:text>Type</xsl:text>
											</span>
										</th>
										<th style="width:auto; " align="left">
											<span style="font-family:Arial; font-size:10pt; font-weight:bold; ">
												<xsl:text>Date</xsl:text>
											</span>
											<span style="font-family:Arial; font-size:9pt; font-weight:bold; ">
												<xsl:text> (</xsl:text>
											</span>
											<span style="font-family:Arial; font-size:9pt; font-style:italic; font-weight:bold; ">
												<xsl:text>mm/dd/yyyy</xsl:text>
											</span>
											<span style="font-family:Arial; font-size:9pt; font-weight:bold; ">
												<xsl:text>)</xsl:text>
											</span>
										</th>
										<th style="width:auto; " align="left">
											<span style="font-family:Arial; font-size:10pt; font-weight:bold; ">
												<xsl:text>Expense</xsl:text>
											</span>
										</th>
									</tr>
								</thead>
								<tbody>
									<xsl:for-each select="expense-item">
										<tr bgcolor="#E0E0E0">
											<td style="width:auto; ">
												<xsl:for-each select="type">
													<xsl:apply-templates/>
												</xsl:for-each>
											</td>
											<td style="width:auto; " align="center">
												<xsl:for-each select="Date">
													<span style="white-space:nowrap; ">
														<xsl:variable name="altova:seqContentStrings_12">
															<xsl:value-of select="format-number(number(substring(string(string(.)), 6, 2)), '00')"/>
															<xsl:text>/</xsl:text>
															<xsl:value-of select="format-number(number(substring(string(string(.)), 9, 2)), '00')"/>
															<xsl:text>/</xsl:text>
															<xsl:value-of select="format-number(number(substring(string(string(string(.))), 1, 4)), '0000')"/>
														</xsl:variable>
														<xsl:variable name="altova:sContent_12" select="string($altova:seqContentStrings_12)"/>
														<xsl:value-of select="$altova:sContent_12"/>
													</span>
													<span>
														<xsl:text>&#160;</xsl:text>
													</span>
												</xsl:for-each>
											</td>
											<td style="width:auto; " align="right">
												<xsl:for-each select="expense">
													<span>
														<xsl:variable name="altova:seqContentStrings_13">
															<xsl:value-of select="format-number(number(string(.)), '###,##0.00')"/>
														</xsl:variable>
														<xsl:variable name="altova:sContent_13" select="string($altova:seqContentStrings_13)"/>
														<xsl:value-of select="$altova:sContent_13"/>
													</span>
												</xsl:for-each>
												<span>
													<xsl:text>&#160;</xsl:text>
												</span>
												<span style="font-weight:bold; ">
													<xsl:text>$</xsl:text>
												</span>
											</td>
										</tr>
									</xsl:for-each>
								</tbody>
							</table>
							<br/>
							<table style="border-collapse:collapse; table-layout:fixed; " border="0" cellpadding="0" cellspacing="0" width="100%">
								<xsl:variable name="altova:CurrContextGrid_14" select="."/>
								<tbody>
									<tr>
										<td style="border-bottom-color:black; border-bottom-style:solid; border-bottom-width:1pt; " bgcolor="#D2FFFF">
											<span style="font-family:Verdana; font-size:14pt; ">
												<xsl:text>Expense Summary</xsl:text>
											</span>
										</td>
									</tr>
								</tbody>
							</table>
							<table style="table-layout:fixed; " border="0" width="100%">
								<xsl:variable name="altova:CurrContextGrid_15" select="."/>
								<tbody>
									<tr>
										<td style="border-color:black; border-style:solid; border-width:1pt; " width="100%">
											<xsl:if test="expense-item/type = &apos;Parking&apos;">
												<table border="0" width="100%">
													<xsl:variable name="altova:CurrContextGrid_16" select="."/>
													<tbody>
														<tr>
															<td style="border-bottom-color:silver; border-bottom-style:solid; border-bottom-width:1pt; " width="47%">
																<span style="font-family:Verdana; ">
																	<xsl:text>Total Parking Expenses</xsl:text>
																</span>
															</td>
															<td style="border-bottom-color:silver; border-bottom-style:solid; border-bottom-width:1pt; white-space:nowrap; " align="right" width="52%">
																<span style="font-family:Verdana; ">
																	<xsl:variable name="altova:seqContentStrings_17">
																		<xsl:value-of select="format-number(number(sum(expense-item[type=&apos;Parking&apos;]/expense)), '###,##0.00')"/>
																	</xsl:variable>
																	<xsl:variable name="altova:sContent_17" select="string($altova:seqContentStrings_17)"/>
																	<xsl:value-of select="$altova:sContent_17"/>
																</span>
																<span>
																	<xsl:text>&#160;</xsl:text>
																</span>
																<span style="font-family:Verdana; font-weight:bold; ">
																	<xsl:text>$</xsl:text>
																</span>
															</td>
															<td style="white-space:nowrap; " width="1%"/>
														</tr>
													</tbody>
												</table>
											</xsl:if>
											<xsl:if test="expense-item/type = &apos;Meal&apos;">
												<table border="0" width="100%">
													<xsl:variable name="altova:CurrContextGrid_18" select="."/>
													<tbody>
														<tr>
															<td style="border-bottom-color:silver; border-bottom-style:solid; border-bottom-width:1pt; white-space:nowrap; " width="47%">
																<span style="font-family:Verdana; ">
																	<xsl:text>Total Meal Expenses</xsl:text>
																</span>
															</td>
															<td style="border-bottom-color:silver; border-bottom-style:solid; border-bottom-width:1pt; white-space:nowrap; " align="right" width="52%">
																<span style="font-family:Verdana; ">
																	<xsl:variable name="altova:seqContentStrings_19">
																		<xsl:value-of select="format-number(number(sum(expense-item[type=&apos;Meal&apos;]/expense)), '###,##0.00')"/>
																	</xsl:variable>
																	<xsl:variable name="altova:sContent_19" select="string($altova:seqContentStrings_19)"/>
																	<xsl:value-of select="$altova:sContent_19"/>
																</span>
																<span style="font-family:Verdana; font-weight:bold; ">
																	<xsl:text> $</xsl:text>
																</span>
															</td>
															<td style="white-space:nowrap; " width="1%"/>
														</tr>
													</tbody>
												</table>
											</xsl:if>
											<xsl:if test="expense-item/type = &apos;Travel&apos;">
												<table border="0" width="100%">
													<xsl:variable name="altova:CurrContextGrid_20" select="."/>
													<tbody>
														<tr>
															<td style="border-bottom-color:silver; border-bottom-style:solid; border-bottom-width:1pt; white-space:nowrap; " width="47%">
																<span style="font-family:Verdana; ">
																	<xsl:text>Total Travel Expenses</xsl:text>
																</span>
															</td>
															<td style="border-bottom-color:silver; border-bottom-style:solid; border-bottom-width:1pt; white-space:nowrap; " align="right" width="52%">
																<span style="font-family:Verdana; ">
																	<xsl:variable name="altova:seqContentStrings_21">
																		<xsl:value-of select="format-number(number(sum(expense-item[type=&apos;Travel&apos;]/expense)), '###,##0.00')"/>
																	</xsl:variable>
																	<xsl:variable name="altova:sContent_21" select="string($altova:seqContentStrings_21)"/>
																	<xsl:value-of select="$altova:sContent_21"/>
																</span>
																<span>
																	<xsl:text>&#160;</xsl:text>
																</span>
																<span style="font-family:Verdana; font-weight:bold; ">
																	<xsl:text>$</xsl:text>
																</span>
															</td>
															<td style="white-space:nowrap; " width="1%"/>
														</tr>
													</tbody>
												</table>
											</xsl:if>
											<xsl:if test="expense-item/type = &apos;Lodging&apos;">
												<table border="0" width="100%">
													<xsl:variable name="altova:CurrContextGrid_22" select="."/>
													<tbody>
														<tr>
															<td style="border-bottom-color:silver; border-bottom-style:solid; border-bottom-width:1pt; white-space:nowrap; " width="47%">
																<span style="font-family:Verdana; ">
																	<xsl:text>Total Lodging Expenses</xsl:text>
																</span>
															</td>
															<td style="border-bottom-color:silver; border-bottom-style:solid; border-bottom-width:1pt; white-space:nowrap; " align="right" width="52%">
																<span style="font-family:Verdana; ">
																	<xsl:variable name="altova:seqContentStrings_23">
																		<xsl:value-of select="format-number(number(sum(expense-item[type=&apos;Lodging&apos;]/expense)), '###,##0.00')"/>
																	</xsl:variable>
																	<xsl:variable name="altova:sContent_23" select="string($altova:seqContentStrings_23)"/>
																	<xsl:value-of select="$altova:sContent_23"/>
																</span>
																<span>
																	<xsl:text>&#160;</xsl:text>
																</span>
																<span style="font-family:Verdana; font-weight:bold; ">
																	<xsl:text>$</xsl:text>
																</span>
															</td>
															<td style="white-space:nowrap; " width="1%"/>
														</tr>
													</tbody>
												</table>
											</xsl:if>
											<xsl:if test="expense-item/type = &apos;Entertainment&apos;">
												<table border="0" width="100%">
													<xsl:variable name="altova:CurrContextGrid_24" select="."/>
													<tbody>
														<tr>
															<td style="border-bottom-color:silver; border-bottom-style:solid; border-bottom-width:1pt; white-space:nowrap; " width="47%">
																<span style="font-family:Verdana; ">
																	<xsl:text>Total Entertainment Expenses</xsl:text>
																</span>
															</td>
															<td style="border-bottom-color:silver; border-bottom-style:solid; border-bottom-width:1pt; white-space:nowrap; " align="right" width="52%">
																<span style="font-family:Verdana; ">
																	<xsl:variable name="altova:seqContentStrings_25">
																		<xsl:value-of select="format-number(number(sum(expense-item[type=&apos;Entertainment&apos;]/expense)), '###,##0.00')"/>
																	</xsl:variable>
																	<xsl:variable name="altova:sContent_25" select="string($altova:seqContentStrings_25)"/>
																	<xsl:value-of select="$altova:sContent_25"/>
																</span>
																<span>
																	<xsl:text>&#160;</xsl:text>
																</span>
																<span style="font-family:Verdana; font-weight:bold; ">
																	<xsl:text>$</xsl:text>
																</span>
															</td>
															<td style="white-space:nowrap; " width="1%"/>
														</tr>
													</tbody>
												</table>
											</xsl:if>
											<xsl:if test="expense-item/type = &apos;Misc&apos;">
												<table border="0" width="100%">
													<xsl:variable name="altova:CurrContextGrid_26" select="."/>
													<tbody>
														<tr>
															<td style="border-bottom-color:silver; border-bottom-style:solid; border-bottom-width:1pt; white-space:nowrap; " width="47%">
																<span style="font-family:Verdana; ">
																	<xsl:text>Total Miscellaneous Expenses</xsl:text>
																</span>
															</td>
															<td style="border-bottom-color:silver; border-bottom-style:solid; border-bottom-width:1pt; white-space:nowrap; " align="right" width="52%">
																<span style="font-family:Verdana; ">
																	<xsl:variable name="altova:seqContentStrings_27">
																		<xsl:value-of select="format-number(number(sum(expense-item[type=&apos;Misc&apos;]/expense)), '###,##0.00')"/>
																	</xsl:variable>
																	<xsl:variable name="altova:sContent_27" select="string($altova:seqContentStrings_27)"/>
																	<xsl:value-of select="$altova:sContent_27"/>
																</span>
																<span>
																	<xsl:text>&#160;</xsl:text>
																</span>
																<span style="font-family:Verdana; font-weight:bold; ">
																	<xsl:text>$</xsl:text>
																</span>
															</td>
															<td style="white-space:nowrap; " width="1%"/>
														</tr>
													</tbody>
												</table>
											</xsl:if>
										</td>
									</tr>
								</tbody>
							</table>
							<table style="table-layout:fixed; " border="0" width="100%">
								<xsl:variable name="altova:CurrContextGrid_28" select="."/>
								<tbody>
									<tr>
										<td width="50%">
											<span style="font-family:Verdana; font-size:medium; ">
												<xsl:text>TOTAL EXPENSES</xsl:text>
											</span>
										</td>
										<td align="right" width="50%">
											<span style="font-family:Verdana; font-size:medium; ">
												<xsl:variable name="altova:seqContentStrings_29">
													<xsl:value-of select="format-number(number(sum( expense-item/expense  )), '###,##0.00')"/>
												</xsl:variable>
												<xsl:variable name="altova:sContent_29" select="string($altova:seqContentStrings_29)"/>
												<xsl:value-of select="$altova:sContent_29"/>
											</span>
											<span>
												<xsl:text>&#160;</xsl:text>
											</span>
											<span style="font-family:Verdana; font-weight:bold; ">
												<xsl:text>$</xsl:text>
											</span>
										</td>
									</tr>
								</tbody>
							</table>
						</xsl:if>
						<br/>
						<table style="table-layout:fixed; " border="0" width="100%">
							<xsl:variable name="altova:CurrContextGrid_30" select="."/>
							<tbody>
								<tr>
									<td colspan="2" align="left" width="15%">
										<span style="font-size:10pt; ">
											<xsl:text>This expense report has exceeded </xsl:text>
										</span>
										<span style="font-size:10pt; font-weight:bold; ">
											<xsl:text>100</xsl:text>
										</span>
										<span style="font-size:10pt; ">
											<xsl:text>$ which under corporate policy requires approval of your direct superior.&#160; All forms must be presented in triplicate and be submitted to the human resources department server in its current XML form.</xsl:text>
										</span>
									</td>
								</tr>
								<tr style="height:101px; ">
									<td style="border-color:#D3D3D3; border-style:solid; border-width:1pt; " valign="bottom" width="15%">
										<table border="0" width="100%">
											<xsl:variable name="altova:CurrContextGrid_31" select="."/>
											<tbody>
												<tr>
													<td/>
												</tr>
												<tr>
													<td>
														<span>
															<xsl:text>Date</xsl:text>
														</span>
													</td>
												</tr>
											</tbody>
										</table>
									</td>
									<td style="border-color:#D3D3D3; border-style:solid; border-width:1pt; " valign="bottom" width="85%">
										<table border="0" width="100%">
											<xsl:variable name="altova:CurrContextGrid_32" select="."/>
											<tbody>
												<tr>
													<td/>
												</tr>
												<tr>
													<td>
														<span>
															<xsl:text>Signature</xsl:text>
														</span>
													</td>
												</tr>
											</tbody>
										</table>
									</td>
								</tr>
							</tbody>
						</table>
						<br/>
					</xsl:for-each>
				</xsl:for-each>
			</body>
		</html>
	</xsl:template>
</xsl:stylesheet>
